version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip3 install -r requirements.txt
      - git version
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - python -c "print('Build Phase Started')"
      - ls -alh
      - python -m PyInstaller terravision.py --onefile --add-data resource_images:resource_images --add-data hcl2:hcl2
      - ls dist/.
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/terravision