"""draw.io shape mapping for Azure resource types.

Auto-generated. Uses img/lib/azure2/ SVG image paths from draw.io.
Style: image;aspect=fixed;html=1;points=[];align=center;fontSize=12;image=<path>;
"""

DRAWIO_SHAPE_MAP_AZURE = {
    "azurerm_api_management": "img/lib/azure2/integration/API_Management_Services.svg",
    "azurerm_app_service": "img/lib/azure2/compute/App_Services.svg",
    "azurerm_application_gateway": "img/lib/azure2/networking/Application_Gateways.svg",
    "azurerm_application_insights": "img/lib/azure2/devops/Application_Insights.svg",
    "azurerm_automation_account": "img/lib/azure2/management_governance/Automation_Accounts.svg",
    "azurerm_availability_set": "img/lib/azure2/compute/Availability_Sets.svg",
    "azurerm_batch_account": "img/lib/azure2/compute/Batch_Accounts.svg",
    "azurerm_cdn_endpoint": "img/lib/azure2/networking/CDN_Profiles.svg",
    "azurerm_container_group": "img/lib/azure2/compute/Container_Instances.svg",
    "azurerm_container_registry": "img/lib/azure2/containers/Container_Registries.svg",
    "azurerm_cosmosdb_account": "img/lib/azure2/databases/Azure_Cosmos_DB.svg",
    "azurerm_data_factory": "img/lib/azure2/databases/Data_Factory.svg",
    "azurerm_dns_zone": "img/lib/azure2/networking/DNS_Zones.svg",
    "azurerm_eventhub_namespace": "img/lib/azure2/analytics/Event_Hubs.svg",
    "azurerm_express_route_circuit": "img/lib/azure2/networking/ExpressRoute_Circuits.svg",
    "azurerm_firewall": "img/lib/azure2/networking/Firewalls.svg",
    "azurerm_frontdoor": "img/lib/azure2/networking/Front_Doors.svg",
    "azurerm_function_app": "img/lib/azure2/compute/Function_Apps.svg",
    "azurerm_iothub": "img/lib/azure2/iot/IoT_Hub.svg",
    "azurerm_key_vault": "img/lib/azure2/security/Key_Vaults.svg",
    "azurerm_kubernetes_cluster": "img/lib/azure2/compute/Kubernetes_Services.svg",
    "azurerm_lb": "img/lib/azure2/networking/Load_Balancers.svg",
    "azurerm_linux_function_app": "img/lib/azure2/compute/Function_Apps.svg",
    "azurerm_linux_virtual_machine": "img/lib/azure2/compute/Virtual_Machine.svg",
    "azurerm_linux_web_app": "img/lib/azure2/compute/App_Services.svg",
    "azurerm_log_analytics_workspace": "img/lib/azure2/analytics/Log_Analytics_Workspaces.svg",
    "azurerm_logic_app_workflow": "img/lib/azure2/integration/Logic_Apps.svg",
    "azurerm_managed_disk": "img/lib/azure2/compute/Disks.svg",
    "azurerm_monitor_action_group": "img/lib/azure2/management_governance/Monitor.svg",
    "azurerm_mssql_database": "img/lib/azure2/databases/SQL_Database.svg",
    "azurerm_mssql_server": "img/lib/azure2/databases/SQL_Server.svg",
    "azurerm_mysql_flexible_server": "img/lib/azure2/databases/Azure_Database_MySQL_Server.svg",
    "azurerm_mysql_server": "img/lib/azure2/databases/Azure_Database_MySQL_Server.svg",
    "azurerm_network_interface": "img/lib/azure2/networking/Network_Interfaces.svg",
    "azurerm_network_security_group": "img/lib/azure2/networking/Network_Security_Groups.svg",
    "azurerm_postgresql_flexible_server": "img/lib/azure2/databases/Azure_Database_PostgreSQL_Server.svg",
    "azurerm_postgresql_server": "img/lib/azure2/databases/Azure_Database_PostgreSQL_Server.svg",
    "azurerm_private_dns_zone": "img/lib/azure2/networking/Private_DNS_Zones.svg",
    "azurerm_private_endpoint": "img/lib/azure2/networking/Private_Endpoints.svg",
    "azurerm_public_ip": "img/lib/azure2/networking/Public_IP_Addresses.svg",
    "azurerm_recovery_services_vault": "img/lib/azure2/management_governance/Recovery_Services_Vaults.svg",
    "azurerm_redis_cache": "img/lib/azure2/databases/Cache_Redis.svg",
    "azurerm_resource_group": "img/lib/azure2/general/Resource_Groups.svg",
    "azurerm_route_table": "img/lib/azure2/networking/Route_Tables.svg",
    "azurerm_service_fabric_cluster": "img/lib/azure2/compute/Service_Fabric_Clusters.svg",
    "azurerm_servicebus_namespace": "img/lib/azure2/integration/Service_Bus.svg",
    "azurerm_sql_server": "img/lib/azure2/databases/SQL_Server.svg",
    "azurerm_storage_account": "img/lib/azure2/storage/Storage_Accounts.svg",
    "azurerm_subnet": "img/lib/azure2/networking/Subnets.svg",
    "azurerm_traffic_manager_profile": "img/lib/azure2/networking/Traffic_Manager_Profiles.svg",
    "azurerm_virtual_machine": "img/lib/azure2/compute/Virtual_Machine.svg",
    "azurerm_virtual_machine_scale_set": "img/lib/azure2/compute/VM_Scale_Sets.svg",
    "azurerm_virtual_network": "img/lib/azure2/networking/Virtual_Networks.svg",
    "azurerm_virtual_network_gateway": "img/lib/azure2/networking/Virtual_Network_Gateways.svg",
    "azurerm_windows_function_app": "img/lib/azure2/compute/Function_Apps.svg",
    "azurerm_windows_virtual_machine": "img/lib/azure2/compute/Virtual_Machine.svg",
    "azurerm_windows_web_app": "img/lib/azure2/compute/App_Services.svg",
    "tv_azurerm_internet": "img/lib/azure2/general/Globe.svg",
    "tv_azurerm_users": "img/lib/azure2/identity/Users.svg",
    "azurerm_public_ip": "img/lib/azure2/networking/Public_IP_Addresses.svg",
    "azurerm_network_interface": "img/lib/azure2/networking/Network_Interfaces.svg",
    "azurerm_virtual_network": "img/lib/azure2/networking/Virtual_Networks.svg",
    "azurerm_subnet": "img/lib/azure2/networking/Subnets.svg",
    "azurerm_resource_group": "img/lib/azure2/general/Resource_Groups.svg",
}
