"""Authoritative draw.io AWS4 shape name sets.

Extracted from jgraph/drawio Sidebar-AWS4.js (v29.6.10).
Used by drawio_emitter.py to determine whether a shape name
uses the resourceIcon pattern or the direct shape pattern.
"""

# Icons that use: shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.<name>
AWS4_RESICON_NAMES = {
    "activate",
    "alexa_for_business",
    "all_products",
    "amplify",
    "analytics",
    "apache_mxnet_on_aws",
    "api_gateway",
    "app_config",
    "app_mesh",
    "app_runner",
    "app_studio",
    "app_wizard",
    "appfabric",
    "appflow",
    "application_auto_scaling",
    "application_composer",
    "application_cost_profiler",
    "application_discovery_service",
    "application_integration",
    "application_recovery_controller",
    "appstream_20",
    "appsync",
    "ar_vr",
    "artifact",
    "athena",
    "audit_manager",
    "augmented_ai",
    "aurora",
    "auto_scaling2",
    "auto_scaling3",
    "autoscaling",
    "b2b_data_interchange",
    "backint_agent",
    "backup",
    "batch",
    "bedrock",
    "bedrock_agentcore",
    "blockchain",
    "bottlerocket",
    "braket",
    "budgets_2",
    "business_application",
    "certificate_manager_3",
    "chatbot",
    "chime",
    "chime_sdk",
    "clean_rooms",
    "client_vpn",
    "cloud9",
    "cloud_control_api",
    "cloud_development_kit",
    "cloud_directory",
    "cloud_map",
    "cloud_wan",
    "cloudendure_disaster_recovery",
    "cloudendure_migration",
    "cloudformation",
    "cloudfront",
    "cloudhsm",
    "cloudsearch2",
    "cloudshell",
    "cloudtrail",
    "cloudwatch_2",
    "codeartifact",
    "codebuild",
    "codecatalyst",
    "codecommit",
    "codedeploy",
    "codeguru",
    "codeguru_2",
    "codepipeline",
    "codestar",
    "codewhisperer",
    "cognito",
    "command_line_interface",
    "comprehend",
    "comprehend_medical",
    "compute",
    "compute_optimizer",
    "config",
    "connect",
    "contact_center",
    "containers",
    "control_tower",
    "corretto",
    "cost_and_usage_report",
    "cost_explorer",
    "cost_management",
    "custom_billing_manager",
    "customer_enablement",
    "customer_engagement",
    "data_exchange",
    "data_pipeline",
    "data_transfer_terminal",
    "database",
    "database_migration_service",
    "datasync",
    "datazone",
    "deadline_cloud",
    "deep_learning_amis",
    "deep_learning_containers",
    "deepcomposer",
    "deeplens",
    "deepracer",
    "desktop_and_app_streaming",
    "detective",
    "developer_tools",
    "device_farm",
    "devops_agent",
    "devops_guru",
    "direct_connect",
    "directory_service",
    "distro_for_opentelemetry",
    "documentdb_with_mongodb_compatibility",
    "dynamodb",
    "ec2",
    "ec2_image_builder",
    "ecr",
    "ecs",
    "ecs_anywhere",
    "efs_infrequentaccess",
    "efs_standard",
    "eks",
    "eks_anywhere",
    "eks_cloud",
    "eks_distro",
    "elastic_beanstalk",
    "elastic_block_store",
    "elastic_fabric_adapter",
    "elastic_file_system",
    "elastic_inference_2",
    "elastic_load_balancing",
    "elastic_transcoder",
    "elastic_vmware_service",
    "elasticache",
    "elasticsearch_service",
    "elemental",
    "elemental_link",
    "elemental_mediaconnect",
    "elemental_mediaconvert",
    "elemental_medialive",
    "elemental_mediapackage",
    "elemental_mediastore",
    "elemental_mediatailor",
    "emr",
    "end_user_messaging",
    "entity_resolution",
    "eventbridge",
    "express_workflow",
    "fargate",
    "fault_injection_simulator",
    "file_cache",
    "finspace",
    "firewall_manager",
    "forecast",
    "fraud_detector",
    "freertos",
    "fsx",
    "fsx_for_lustre",
    "fsx_for_netapp_ontap",
    "fsx_for_openzfs",
    "fsx_for_windows_file_server",
    "gamekit",
    "gamelift_2",
    "gamelift_streams",
    "games",
    "gamesparks",
    "general",
    "genomics_cli",
    "glacier",
    "global_accelerator",
    "glue",
    "glue_databrew",
    "glue_elastic_views",
    "greengrass",
    "ground_station",
    "guardduty",
    "healthimaging",
    "healthlake",
    "healthscribe",
    "honeycode",
    "identity_and_access_management",
    "infrequent_access_storage_class",
    "inspector",
    "interactive_video",
    "internet_of_things",
    "iot_1click",
    "iot_analytics",
    "iot_button",
    "iot_core",
    "iot_device_defender",
    "iot_device_management",
    "iot_edukit",
    "iot_events",
    "iot_expresslink",
    "iot_fleetwise",
    "iot_roborunner",
    "iot_sitewise",
    "iot_things_graph",
    "iot_twinmaker",
    "iq",
    "kendra",
    "key_management_service",
    "keyspaces",
    "kinesis",
    "kinesis_data_analytics",
    "kinesis_data_firehose",
    "kinesis_data_streams",
    "kinesis_video_streams",
    "lake_formation",
    "lambda",
    "lex",
    "license_manager",
    "lightsail",
    "lightsail_for_research",
    "local_zones",
    "location_service",
    "lookout_for_equipment",
    "lookout_for_metrics",
    "lookout_for_vision",
    "lumberyard",
    "machine_learning",
    "macie",
    "mainframe_modernization",
    "managed_apache_cassandra_service",
    "managed_blockchain",
    "managed_service_for_apache_flink",
    "managed_service_for_grafana",
    "managed_service_for_prometheus",
    "managed_services",
    "managed_streaming_for_kafka",
    "managed_workflows_for_apache_airflow",
    "management_and_governance",
    "management_console",
    "marketplace",
    "media_services",
    "memorydb_for_redis",
    "migration_and_transfer",
    "migration_evaluator",
    "migration_hub",
    "mobile",
    "mobile_application",
    "monitron",
    "mq",
    "neptune",
    "network_firewall",
    "networking_and_content_delivery",
    "neuron_ml_sdk",
    "nice_dcv",
    "nice_enginframe",
    "nimble_studio",
    "nitro_enclaves",
    "nova2",
    "omics",
    "open_3d_engine_2",
    "opsworks",
    "oracle_database_at_aws",
    "organizations",
    "outposts",
    "outposts_1u_and_2u_servers",
    "outposts_family",
    "panorama",
    "parallel_cluster",
    "parallel_computing_service",
    "partner_central",
    "payment_cryptography",
    "personal_health_dashboard",
    "personalize",
    "pinpoint",
    "polly",
    "private_5g",
    "private_certificate_authority",
    "professional_services",
    "proton",
    "q",
    "quantum_ledger_database",
    "quantum_technologies",
    "quick_suite",
    "quicksight",
    "rds",
    "rds_on_vmware",
    "red_hat_openshift",
    "redshift",
    "rekognition_2",
    "repost",
    "repost_private",
    "reserved_instance_reporting",
    "resilience_hub",
    "resource_access_manager",
    "resource_explorer",
    "robomaker",
    "robotics",
    "route_53",
    "rtb_fabric",
    "s3",
    "s3_on_outposts_storage",
    "sagemaker",
    "sagemaker_2",
    "sagemaker_ground_truth",
    "sagemaker_studio_lab",
    "satellite",
    "savings_plans",
    "secrets_manager",
    "security_agent",
    "security_hub",
    "security_identity_and_compliance",
    "security_incident_response",
    "security_lake",
    "server_migration_service",
    "serverless",
    "serverless_application_repository",
    "service_catalog",
    "service_management_connector",
    "shield",
    "signer",
    "simple_email_service",
    "simspace_weaver",
    "single_sign_on",
    "site_to_site_vpn",
    "snowball",
    "snowball_edge",
    "snowcone",
    "snowmobile",
    "sns",
    "sql_workbench",
    "sqs",
    "step_functions",
    "storage",
    "storage_gateway",
    "sumerian",
    "supply_chain",
    "support",
    "systems_manager",
    "systems_manager_incident_manager",
    "telco_network_builder",
    "tensorflow_on_aws",
    "textract",
    "thinkbox_deadline",
    "thinkbox_draft",
    "thinkbox_frost",
    "thinkbox_krakatoa",
    "thinkbox_sequoia",
    "thinkbox_stoke",
    "thinkbox_xmesh",
    "timestream",
    "tools_and_sdks",
    "torchserve",
    "training_certification",
    "transcribe",
    "transfer_family",
    "transfer_for_sftp",
    "transform",
    "transit_gateway",
    "translate",
    "trusted_advisor",
    "user_notifications",
    "verified_access",
    "verified_permissions",
    "vmware_cloud_on_aws",
    "vpc",
    "vpc_lattice",
    "vpc_privatelink",
    "waf",
    "wavelength",
    "well_architect_tool",
    "wickr",
    "workdocs",
    "worklink",
    "workmail",
    "workspaces",
    "workspaces_family",
    "workspaces_thin_client",
    "xray",
}

# Icons that use: shape=mxgraph.aws4.<name> (direct shape)
AWS4_DIRECT_SHAPE_NAMES = {
    "a1_instance",
    "access_analyzer",
    "action",
    "actuator",
    "ad_connector",
    "addon",
    "agent",
    "agent2",
    "alarm",
    "alert",
    "alexa_enabled_device",
    "alexa_skill",
    "all_products",
    "ami",
    "amplify_aws_amplify_studio",
    "application",
    "application_discovery_service_aws_agentless_collector",
    "application_discovery_service_aws_discovery_agent",
    "application_discovery_service_migration_evaluator_collector",
    "application_load_balancer",
    "archive",
    "athena_data_source_connectors",
    "attribute",
    "attributes",
    "aurora_instance",
    "aurora_instance_alt",
    "authenticated_user",
    "auto_scaling2",
    "automation",
    "aws_backup_for_aws_cloudformation",
    "aws_backup_legal_hold",
    "aws_backup_support_for_amazon_fsx_for_netapp_ontap",
    "aws_backup_vault_lock",
    "aws_glue_data_quality",
    "aws_glue_for_ray",
    "backup_audit_manager",
    "backup_aws_backup_support_for_amazon_s3",
    "backup_aws_backup_support_for_vmware_workloads",
    "backup_compliance_reporting",
    "backup_compute",
    "backup_database",
    "backup_gateway",
    "backup_plan",
    "backup_recovery_point_objective",
    "backup_recovery_time_objective",
    "backup_restore",
    "backup_storage",
    "backup_vault",
    "backup_virtual_machine",
    "backup_virtual_machine_monitor",
    "bank",
    "blockchain_resource",
    "braket_chandelier",
    "braket_chip",
    "braket_embedded_simulator",
    "braket_managed_simulator",
    "braket_noise_simulator",
    "braket_qpu",
    "braket_simulator",
    "braket_simulator_1",
    "braket_simulator_2",
    "braket_simulator_3",
    "braket_simulator_4",
    "braket_state_vector",
    "braket_tensor_network",
    "bucket",
    "bucket_with_objects",
    "bycicle",
    "c4_instance",
    "c5_instance",
    "c5a",
    "c5ad",
    "c5d",
    "c5n_instance",
    "c6g_instance",
    "c6gd",
    "cache_node",
    "cached_volume",
    "camera",
    "camera2",
    "car",
    "cart",
    "certificate_manager",
    "certificate_manager_2",
    "change_set",
    "chat",
    "checklist",
    "checklist_cost",
    "checklist_fault_tolerant",
    "checklist_performance",
    "checklist_security",
    "classic_load_balancer",
    "client",
    "cloud9",
    "cloud_digital_interface",
    "cloud_extension_ros",
    "cloud_wan_segment_network",
    "cloud_wan_transit_gateway_route_table_attachment",
    "cloud_wan_virtual_pop",
    "cloudfront_functions",
    "cloudtrail_cloudtrail_lake",
    "cloudwatch_cross_account_observability",
    "cloudwatch_data_protection",
    "cloudwatch_evidently",
    "cloudwatch_logs",
    "cloudwatch_metrics_insights",
    "cloudwatch_rum",
    "cloudwatch_synthetics",
    "cluster",
    "coffee_pot",
    "cold_storage",
    "connector",
    "container_1",
    "container_2",
    "container_3",
    "container_registry_image",
    "corporate_data_center",
    "credentials",
    "customer_gateway",
    "d2_instance",
    "d3_instance",
    "d3en_instance",
    "data_encryption_key",
    "data_exchange_for_apis",
    "data_lake_resource_icon",
    "data_set",
    "data_stream",
    "data_table",
    "database_migration_workflow_job",
    "datasync_discovery",
    "datazone_business_data_catalog",
    "datazone_data_portal",
    "datazone_data_projects",
    "db_on_instance2",
    "dense_compute_node",
    "dense_storage_node",
    "deployment",
    "deployments",
    "desired_state",
    "development_environment",
    "devops_guru_insights",
    "disk",
    "document",
    "documentdb_elastic_clusters",
    "documents",
    "documents2",
    "documents3",
    "door_lock",
    "download_distribution",
    "dynamodb_dax",
    "dynamodb_standard_access_table_class",
    "dynamodb_standard_infrequent_access_table_class",
    "dynamodb_stream",
    "ec2_aws_microservice_extractor_for_net",
    "ec2_c6a_instance",
    "ec2_c6gn_instance",
    "ec2_c6i_instance",
    "ec2_c6in_instance",
    "ec2_c7g_instance",
    "ec2_c7gn_instance",
    "ec2_dl1_instance",
    "ec2_g5_instance",
    "ec2_g5g_instance",
    "ec2_hpc6a_instance",
    "ec2_hpc6id_instance",
    "ec2_i4i_instance",
    "ec2_im4gn_instance",
    "ec2_inf2_instance",
    "ec2_is4gen_instance",
    "ec2_m1_mac_instance",
    "ec2_m6a_instance",
    "ec2_m6i_instance",
    "ec2_m6idn_instance",
    "ec2_m6in_instance",
    "ec2_p4de_instance",
    "ec2_r6a_instance",
    "ec2_r6i_instance",
    "ec2_r6idn_instance",
    "ec2_r6in_instance",
    "ec2_r7iz_instance",
    "ec2_trn1_instance",
    "ec2_vt1_instance",
    "ec2_x2gd_instance",
    "ec2_x2idn_instance",
    "ec2_x2iedn_instance",
    "ec2_x2iezn_instance",
    "echo",
    "ecs_anywhere",
    "ecs_copilot_cli",
    "ecs_service",
    "ecs_service_connect",
    "ecs_task",
    "edge_location",
    "eks_on_outposts",
    "elastic_block_store_amazon_data_lifecycle_manager",
    "elastic_block_store_volume_gp3",
    "elastic_file_system_elastic_throughput",
    "elastic_file_system_infrequent_access",
    "elastic_file_system_intelligent_tiering",
    "elastic_file_system_one_zone",
    "elastic_file_system_one_zone_infrequent_access",
    "elastic_file_system_standard",
    "elastic_ip_address",
    "elastic_network_adapter",
    "elastic_network_interface",
    "elasticache_for_memcached",
    "elasticache_for_redis",
    "elasticache_for_valkey",
    "email",
    "email_2",
    "email_notification",
    "emr_engine",
    "emr_engine_mapr_m3",
    "emr_engine_mapr_m5",
    "emr_engine_mapr_m7",
    "encrypted_data",
    "endpoint",
    "endpoints",
    "event",
    "event_event_based",
    "event_resource",
    "event_time_based",
    "eventbridge_custom_event_bus_resource",
    "eventbridge_default_event_bus_resource",
    "eventbridge_pipes",
    "eventbridge_saas_partner_event_bus_resource",
    "eventbridge_scheduler",
    "eventbridge_schema",
    "eventbridge_schema_registry",
    "external_sdk",
    "external_toolkit",
    "f1_instance",
    "factory",
    "file_cache_hybrid_nfs_linked_datasets",
    "file_cache_on_premises_nfs_linked_datasets",
    "file_cache_s3_linked_datasets",
    "file_gateway",
    "file_system",
    "filtering_rule",
    "finding",
    "firetv",
    "firetv_stick",
    "fleet_management",
    "flow_logs",
    "folder",
    "folders",
    "forums",
    "fsx_file_gateway",
    "g3_instance",
    "g4ad_instance",
    "g4dn",
    "gateway",
    "gateway_load_balancer",
    "gear",
    "general_access_points",
    "generic",
    "generic_application",
    "generic_database",
    "generic_firewall",
    "git_repository",
    "glacier",
    "glacier_deep_archive",
    "global_secondary_index",
    "globe",
    "glue_crawlers",
    "glue_data_catalog",
    "glue_databrew",
    "h1_instance",
    "habana_gaudi",
    "hardware_board",
    "hdfs_cluster",
    "high_memory_instance",
    "hosted_zone",
    "house",
    "http2_protocol",
    "http_notification",
    "http_protocol",
    "i2",
    "i3_instance",
    "i3en",
    "identity_access_management_iam_roles_anywhere",
    "import_export",
    "inf1",
    "inferentia",
    "instance2",
    "instance_with_cloudwatch2",
    "instances",
    "instances_2",
    "intelligent_tiering",
    "internet",
    "internet_alt1",
    "internet_alt2",
    "internet_alt22",
    "internet_gateway",
    "inventory",
    "iot_analytics_channel",
    "iot_analytics_data_store",
    "iot_analytics_pipeline",
    "iot_core_device_advisor",
    "iot_core_device_location",
    "iot_device_gateway",
    "iot_device_jobs_resource",
    "iot_device_management_fleet",
    "iot_device_tester",
    "iot_greengrass_artifact",
    "iot_greengrass_component",
    "iot_greengrass_component_machine_learning",
    "iot_greengrass_component_nucleus",
    "iot_greengrass_component_private",
    "iot_greengrass_component_public",
    "iot_greengrass_interprocess_communication",
    "iot_greengrass_protocol",
    "iot_greengrass_recipe",
    "iot_greengrass_stream_manager",
    "iot_lorawan_protocol",
    "iot_over_the_air_update",
    "iot_sailboat",
    "iot_sitewise_asset",
    "iot_sitewise_asset_hierarchy",
    "iot_sitewise_asset_model",
    "iot_sitewise_asset_properties",
    "iot_sitewise_data_streams",
    "iot_thing_freertos_device",
    "iot_thing_humidity_sensor",
    "iot_thing_industrial_pc",
    "iot_thing_plc",
    "iot_thing_relay",
    "iot_thing_stacklight",
    "iot_thing_temperature_humidity_sensor",
    "iot_thing_temperature_sensor",
    "iot_thing_temperature_vibration_sensor",
    "iot_thing_vibration_sensor",
    "item",
    "items",
    "json_script",
    "key_management_service_external_key_store",
    "lambda_function",
    "layers",
    "license_manager_application_discovery",
    "license_manager_license_blending",
    "lightbulb",
    "location_service_geofence",
    "location_service_map",
    "location_service_place",
    "location_service_routes",
    "location_service_track",
    "logs",
    "long_term_security_credential",
    "m4_instance",
    "m5_instance",
    "m5a_instance",
    "m5d_instance",
    "m5dn_instance",
    "m5n_instance",
    "m5zn_instance",
    "m6g_instance",
    "m6gd_instance",
    "mac_instance",
    "magnifying_glass_2",
    "mainframe_modernization_analyzer",
    "mainframe_modernization_compiler",
    "mainframe_modernization_converter",
    "mainframe_modernization_developer",
    "mainframe_modernization_runtime",
    "maintenance_windows",
    "managed_ms_ad",
    "management_console2",
    "marketplace",
    "mediaconnect_gateway",
    "medical_emergency",
    "mesh",
    "message",
    "metrics",
    "mfa_token",
    "migration_hub_refactor_spaces_applications",
    "migration_hub_refactor_spaces_environments",
    "migration_hub_refactor_spaces_services",
    "mobile_client",
    "monitoring",
    "mq_broker",
    "mqtt_protocol",
    "msk_amazon_msk_connect",
    "multimedia",
    "multiple_volumes_resource",
    "namespace",
    "nat_gateway",
    "network_access_control_list",
    "network_firewall_endpoints",
    "network_load_balancer",
    "non_cached_volume",
    "notebook",
    "object",
    "office_building",
    "one_zone_ia",
    "opensearch_dashboards",
    "opensearch_ingestion",
    "opensearch_observability",
    "opensearch_service_cluster_administrator_node",
    "opensearch_service_data_node",
    "opensearch_service_index",
    "opensearch_service_traces",
    "opensearch_service_ultrawarm_node",
    "opsworks_apps",
    "opsworks_permissions",
    "optimized_instance",
    "organizations_account",
    "organizations_account2",
    "organizations_management_account",
    "organizations_management_account2",
    "organizations_organizational_unit",
    "organizations_organizational_unit2",
    "p2_instance",
    "p3_instance",
    "p3dn_instance",
    "p4_instance",
    "p4d_instance",
    "parameter_store",
    "patch_manager",
    "peering",
    "permissions",
    "pinpoint_journey",
    "police_emergency",
    "policy",
    "programming_language",
    "question",
    "queue",
    "quicksight_paginated_reports",
    "r4_instance",
    "r5_instance",
    "r5a_instance",
    "r5ad_instance",
    "r5b_instance",
    "r5d_instance",
    "r5gd_instance",
    "r5n_instance",
    "r6g_instance",
    "rdn_instance",
    "rds_blue_green_deployments",
    "rds_instance",
    "rds_instance_alt",
    "rds_mariadb_instance",
    "rds_mariadb_instance_alt",
    "rds_multi_az",
    "rds_multi_az_db_cluster",
    "rds_mysql_instance",
    "rds_mysql_instance_alt",
    "rds_optimized_writes",
    "rds_oracle_instance",
    "rds_oracle_instance_alt",
    "rds_piops",
    "rds_postgresql_instance",
    "rds_postgresql_instance_alt",
    "rds_proxy",
    "rds_proxy_alt",
    "rds_sql_server_instance",
    "rds_sql_server_instance_alt",
    "rds_trusted_language_extensions_for_postgresql",
    "recover",
    "redshift_auto_copy",
    "redshift_data_sharing_governance",
    "redshift_ml",
    "redshift_query_editor_v20_light",
    "redshift_ra3",
    "redshift_streaming_ingestion",
    "registry",
    "rekognition_image",
    "rekognition_video",
    "replication",
    "replication_time_control",
    "reported_state",
    "rescue",
    "resource",
    "resources",
    "role",
    "route_53_application_recovery_controller",
    "route_53_readiness_checks",
    "route_53_resolver",
    "route_53_resolver_dns_firewall",
    "route_53_resolver_query_logging",
    "route_53_routing_controls",
    "route_table",
    "router",
    "rule",
    "rule_2",
    "rule_3",
    "run_command",
    "s3_batch_operations",
    "s3_express_one_zone",
    "s3_file_gateway",
    "s3_multi_region_access_points",
    "s3_object_lambda",
    "s3_object_lambda_access_points",
    "s3_object_lock",
    "s3_on_outposts",
    "s3_select",
    "s3_storage_lens",
    "s3_tables",
    "s3_vectors",
    "sagemaker_canvas",
    "sagemaker_geospatial_ml",
    "sagemaker_model",
    "sagemaker_notebook",
    "sagemaker_shadow_testing",
    "sagemaker_train",
    "saml_token",
    "search_documents",
    "sensor",
    "servers",
    "service",
    "servo",
    "shadow",
    "shield2",
    "shield_shield_advanced",
    "simple_ad",
    "simple_storage_service_directory_bucket",
    "simple_storage_service_s3_glacier_instant_retrieval",
    "simulation",
    "simulator",
    "snapshot",
    "source_code",
    "spot_instance",
    "ssl_padlock",
    "stack",
    "stack2",
    "standard_ia",
    "state_manager",
    "streaming_distribution",
    "sts",
    "sts_alternate",
    "systems_manager_application_manager",
    "systems_manager_change_calendar",
    "systems_manager_change_manager",
    "systems_manager_compliance",
    "systems_manager_distributor",
    "systems_manager_incident_manager",
    "systems_manager_opscenter",
    "systems_manager_session_manager",
    "t2_instance",
    "t3_instance",
    "t3a_instance",
    "t4g_instance",
    "table",
    "tape_gateway",
    "tape_storage",
    "template",
    "temporary_security_credential",
    "textract_analyze_lending",
    "thermostat",
    "topic",
    "topic_2",
    "traditional_server",
    "trainium_instance",
    "transfer_family_aws_as2",
    "transfer_for_ftp_resource",
    "transfer_for_ftps_resource",
    "transfer_for_sftp_resource",
    "transit_gateway_attachment",
    "travel",
    "user",
    "users",
    "utility",
    "vault",
    "virtual_gateway",
    "virtual_node",
    "virtual_router",
    "virtual_service",
    "virtual_tape_library",
    "volume",
    "volume_gateway",
    "vpc_access_points",
    "vpc_carrier_gateway",
    "vpc_network_access_analyzer",
    "vpc_reachability_analyzer",
    "vpc_traffic_mirroring",
    "vpc_virtual_private_cloud_vpc",
    "vpn_connection",
    "vpn_gateway",
    "waf_bad_bot",
    "waf_bot",
    "waf_bot_control",
    "waf_labels",
    "waf_managed_rule",
    "waf_rule",
    "windfarm",
    "workspaces_family_amazon_workspaces",
    "workspaces_family_amazon_workspaces_core",
    "workspaces_workspaces_web",
    "x1_instance2",
    "x1e_instance",
    "z1d_instance",
}

# Fill color for each direct shape (from Sidebar-AWS4.js section context)
AWS4_DIRECT_SHAPE_FILLS = {
    "a1_instance": "#ED7100",
    "access_analyzer": "#DD344C",
    "action": "#7AA116",
    "actuator": "#7AA116",
    "ad_connector": "#DD344C",
    "addon": "#DD344C",
    "agent": "#DD344C",
    "agent2": "#01A88D",
    "alarm": "#E7157B",
    "alert": "#5A6C86",
    "alexa_enabled_device": "#7AA116",
    "alexa_skill": "#7AA116",
    "all_products": "#5A6C86",
    "ami": "#ED7100",
    "amplify_aws_amplify_studio": "#DD344C",
    "application": "#ED7100",
    "application_discovery_service_aws_agentless_collector": "#01A88D",
    "application_discovery_service_aws_discovery_agent": "#01A88D",
    "application_discovery_service_migration_evaluator_collector": "#01A88D",
    "application_load_balancer": "#8C4FFF",
    "archive": "#7AA116",
    "athena_data_source_connectors": "#8C4FFF",
    "attribute": "#C925D1",
    "attributes": "#C925D1",
    "aurora_instance": "#C925D1",
    "aurora_instance_alt": "#C925D1",
    "authenticated_user": "#5A6C86",
    "auto_scaling2": "#ED7100",
    "automation": "#E7157B",
    "aws_backup_for_aws_cloudformation": "#7AA116",
    "aws_backup_legal_hold": "#7AA116",
    "aws_backup_support_for_amazon_fsx_for_netapp_ontap": "#7AA116",
    "aws_backup_vault_lock": "#7AA116",
    "aws_glue_data_quality": "#8C4FFF",
    "aws_glue_for_ray": "#8C4FFF",
    "backup_audit_manager": "#7AA116",
    "backup_aws_backup_support_for_amazon_s3": "#7AA116",
    "backup_aws_backup_support_for_vmware_workloads": "#7AA116",
    "backup_compliance_reporting": "#7AA116",
    "backup_compute": "#7AA116",
    "backup_database": "#7AA116",
    "backup_gateway": "#7AA116",
    "backup_plan": "#7AA116",
    "backup_recovery_point_objective": "#7AA116",
    "backup_recovery_time_objective": "#7AA116",
    "backup_restore": "#7AA116",
    "backup_storage": "#7AA116",
    "backup_vault": "#7AA116",
    "backup_virtual_machine": "#7AA116",
    "backup_virtual_machine_monitor": "#7AA116",
    "bank": "#7AA116",
    "blockchain_resource": "#ED7100",
    "braket_chandelier": "#ED7100",
    "braket_chip": "#ED7100",
    "braket_embedded_simulator": "#ED7100",
    "braket_managed_simulator": "#ED7100",
    "braket_noise_simulator": "#ED7100",
    "braket_qpu": "#ED7100",
    "braket_simulator": "#ED7100",
    "braket_simulator_1": "#ED7100",
    "braket_simulator_2": "#ED7100",
    "braket_simulator_3": "#ED7100",
    "braket_simulator_4": "#ED7100",
    "braket_state_vector": "#ED7100",
    "braket_tensor_network": "#ED7100",
    "bucket": "#7AA116",
    "bucket_with_objects": "#7AA116",
    "bycicle": "#7AA116",
    "c4_instance": "#ED7100",
    "c5_instance": "#ED7100",
    "c5a": "#ED7100",
    "c5ad": "#ED7100",
    "c5d": "#ED7100",
    "c5n_instance": "#ED7100",
    "c6g_instance": "#ED7100",
    "c6gd": "#ED7100",
    "cache_node": "#C925D1",
    "cached_volume": "#7AA116",
    "camera": "#7AA116",
    "camera2": "#5A6C86",
    "car": "#7AA116",
    "cart": "#7AA116",
    "certificate_manager": "#7AA116",
    "certificate_manager_2": "#DD344C",
    "change_set": "#E7157B",
    "chat": "#5A6C86",
    "checklist": "#E7157B",
    "checklist_cost": "#E7157B",
    "checklist_fault_tolerant": "#E7157B",
    "checklist_performance": "#E7157B",
    "checklist_security": "#E7157B",
    "classic_load_balancer": "#8C4FFF",
    "client": "#5A6C86",
    "cloud9": "#C925D1",
    "cloud_digital_interface": "#ED7100",
    "cloud_extension_ros": "#DD344C",
    "cloud_wan_segment_network": "#8C4FFF",
    "cloud_wan_transit_gateway_route_table_attachment": "#8C4FFF",
    "cloud_wan_virtual_pop": "#8C4FFF",
    "cloudfront_functions": "#8C4FFF",
    "cloudtrail_cloudtrail_lake": "#E7157B",
    "cloudwatch_cross_account_observability": "#E7157B",
    "cloudwatch_data_protection": "#E7157B",
    "cloudwatch_evidently": "#E7157B",
    "cloudwatch_logs": "#E7157B",
    "cloudwatch_metrics_insights": "#E7157B",
    "cloudwatch_rum": "#E7157B",
    "cloudwatch_synthetics": "#E7157B",
    "cluster": "#8C4FFF",
    "coffee_pot": "#7AA116",
    "cold_storage": "#5A6C86",
    "connector": "#7AA116",
    "container_1": "#ED7100",
    "container_2": "#ED7100",
    "container_3": "#ED7100",
    "container_registry_image": "#ED7100",
    "corporate_data_center": "#5A6C86",
    "credentials": "#5A6C86",
    "customer_gateway": "#8C4FFF",
    "d2_instance": "#ED7100",
    "d3_instance": "#ED7100",
    "d3en_instance": "#ED7100",
    "data_encryption_key": "#DD344C",
    "data_exchange_for_apis": "#8C4FFF",
    "data_lake_resource_icon": "#8C4FFF",
    "data_set": "#7AA116",
    "data_stream": "#5A6C86",
    "data_table": "#5A6C86",
    "database_migration_workflow_job": "#C925D1",
    "datasync_discovery": "#01A88D",
    "datazone_business_data_catalog": "#8C4FFF",
    "datazone_data_portal": "#8C4FFF",
    "datazone_data_projects": "#8C4FFF",
    "db_on_instance2": "#ED7100",
    "dense_compute_node": "#C925D1",
    "dense_storage_node": "#C925D1",
    "deployment": "#ED7100",
    "deployments": "#E7157B",
    "desired_state": "#7AA116",
    "development_environment": "#DD344C",
    "devops_guru_insights": "#01A88D",
    "disk": "#5A6C86",
    "document": "#5A6C86",
    "documentdb_elastic_clusters": "#C925D1",
    "documents": "#E7157B",
    "documents2": "#5A6C86",
    "documents3": "#5A6C86",
    "door_lock": "#7AA116",
    "download_distribution": "#8C4FFF",
    "dynamodb_dax": "#C925D1",
    "dynamodb_standard_access_table_class": "#C925D1",
    "dynamodb_standard_infrequent_access_table_class": "#C925D1",
    "dynamodb_stream": "#C925D1",
    "ec2_aws_microservice_extractor_for_net": "#ED7100",
    "ec2_c6a_instance": "#ED7100",
    "ec2_c6gn_instance": "#ED7100",
    "ec2_c6i_instance": "#ED7100",
    "ec2_c6in_instance": "#ED7100",
    "ec2_c7g_instance": "#ED7100",
    "ec2_c7gn_instance": "#ED7100",
    "ec2_dl1_instance": "#ED7100",
    "ec2_g5_instance": "#ED7100",
    "ec2_g5g_instance": "#ED7100",
    "ec2_hpc6a_instance": "#ED7100",
    "ec2_hpc6id_instance": "#ED7100",
    "ec2_i4i_instance": "#ED7100",
    "ec2_im4gn_instance": "#ED7100",
    "ec2_inf2_instance": "#ED7100",
    "ec2_is4gen_instance": "#ED7100",
    "ec2_m1_mac_instance": "#ED7100",
    "ec2_m6a_instance": "#ED7100",
    "ec2_m6i_instance": "#ED7100",
    "ec2_m6idn_instance": "#ED7100",
    "ec2_m6in_instance": "#ED7100",
    "ec2_p4de_instance": "#ED7100",
    "ec2_r6a_instance": "#ED7100",
    "ec2_r6i_instance": "#ED7100",
    "ec2_r6idn_instance": "#ED7100",
    "ec2_r6in_instance": "#ED7100",
    "ec2_r7iz_instance": "#ED7100",
    "ec2_trn1_instance": "#ED7100",
    "ec2_vt1_instance": "#ED7100",
    "ec2_x2gd_instance": "#ED7100",
    "ec2_x2idn_instance": "#ED7100",
    "ec2_x2iedn_instance": "#ED7100",
    "ec2_x2iezn_instance": "#ED7100",
    "echo": "#7AA116",
    "ecs_anywhere": "#ED7100",
    "ecs_copilot_cli": "#ED7100",
    "ecs_service": "#ED7100",
    "ecs_service_connect": "#ED7100",
    "ecs_task": "#ED7100",
    "edge_location": "#8C4FFF",
    "eks_on_outposts": "#ED7100",
    "elastic_block_store_amazon_data_lifecycle_manager": "#7AA116",
    "elastic_block_store_volume_gp3": "#7AA116",
    "elastic_file_system_elastic_throughput": "#7AA116",
    "elastic_file_system_infrequent_access": "#7AA116",
    "elastic_file_system_intelligent_tiering": "#7AA116",
    "elastic_file_system_one_zone": "#7AA116",
    "elastic_file_system_one_zone_infrequent_access": "#7AA116",
    "elastic_file_system_standard": "#7AA116",
    "elastic_ip_address": "#ED7100",
    "elastic_network_adapter": "#8C4FFF",
    "elastic_network_interface": "#8C4FFF",
    "elasticache_for_memcached": "#C925D1",
    "elasticache_for_redis": "#C925D1",
    "elasticache_for_valkey": "#C925D1",
    "email": "#DD344C",
    "email_2": "#5A6C86",
    "email_notification": "#E7157B",
    "emr_engine": "#8C4FFF",
    "emr_engine_mapr_m3": "#8C4FFF",
    "emr_engine_mapr_m5": "#8C4FFF",
    "emr_engine_mapr_m7": "#8C4FFF",
    "encrypted_data": "#DD344C",
    "endpoint": "#8C4FFF",
    "endpoints": "#8C4FFF",
    "event": "#E7157B",
    "event_event_based": "#E7157B",
    "event_resource": "#E7157B",
    "event_time_based": "#E7157B",
    "eventbridge_custom_event_bus_resource": "#E7157B",
    "eventbridge_default_event_bus_resource": "#E7157B",
    "eventbridge_pipes": "#E7157B",
    "eventbridge_saas_partner_event_bus_resource": "#E7157B",
    "eventbridge_scheduler": "#E7157B",
    "eventbridge_schema": "#E7157B",
    "eventbridge_schema_registry": "#E7157B",
    "external_sdk": "#5A6C86",
    "external_toolkit": "#5A6C86",
    "f1_instance": "#ED7100",
    "factory": "#7AA116",
    "file_cache_hybrid_nfs_linked_datasets": "#7AA116",
    "file_cache_on_premises_nfs_linked_datasets": "#7AA116",
    "file_cache_s3_linked_datasets": "#7AA116",
    "file_gateway": "#7AA116",
    "file_system": "#7AA116",
    "filtering_rule": "#DD344C",
    "finding": "#DD344C",
    "firetv": "#7AA116",
    "firetv_stick": "#7AA116",
    "fleet_management": "#DD344C",
    "flow_logs": "#8C4FFF",
    "folder": "#5A6C86",
    "folders": "#5A6C86",
    "forums": "#5A6C86",
    "fsx_file_gateway": "#7AA116",
    "g3_instance": "#ED7100",
    "g4ad_instance": "#ED7100",
    "g4dn": "#ED7100",
    "gateway": "#8C4FFF",
    "gateway_load_balancer": "#8C4FFF",
    "gear": "#5A6C86",
    "general_access_points": "#7AA116",
    "generic": "#7AA116",
    "generic_application": "#5A6C86",
    "generic_database": "#5A6C86",
    "generic_firewall": "#5A6C86",
    "git_repository": "#5A6C86",
    "glacier": "#7AA116",
    "glacier_deep_archive": "#7AA116",
    "global_secondary_index": "#C925D1",
    "globe": "#5A6C86",
    "glue_crawlers": "#8C4FFF",
    "glue_data_catalog": "#8C4FFF",
    "glue_databrew": "#8C4FFF",
    "h1_instance": "#ED7100",
    "habana_gaudi": "#ED7100",
    "hardware_board": "#7AA116",
    "hdfs_cluster": "#8C4FFF",
    "high_memory_instance": "#ED7100",
    "hosted_zone": "#8C4FFF",
    "house": "#7AA116",
    "http2_protocol": "#7AA116",
    "http_notification": "#E7157B",
    "http_protocol": "#7AA116",
    "i2": "#ED7100",
    "i3_instance": "#ED7100",
    "i3en": "#ED7100",
    "identity_access_management_iam_roles_anywhere": "#DD344C",
    "import_export": "#7AA116",
    "inf1": "#ED7100",
    "inferentia": "#ED7100",
    "instance2": "#ED7100",
    "instance_with_cloudwatch2": "#ED7100",
    "instances": "#ED7100",
    "instances_2": "#E7157B",
    "intelligent_tiering": "#7AA116",
    "internet": "#232F3D",
    "internet_alt1": "#5A6C86",
    "internet_alt2": "#232F3D",
    "internet_alt22": "#5A6C86",
    "internet_gateway": "#8C4FFF",
    "inventory": "#E7157B",
    "iot_analytics_channel": "#7AA116",
    "iot_analytics_data_store": "#7AA116",
    "iot_analytics_pipeline": "#7AA116",
    "iot_core_device_advisor": "#7AA116",
    "iot_core_device_location": "#7AA116",
    "iot_device_gateway": "#7AA116",
    "iot_device_jobs_resource": "#7AA116",
    "iot_device_management_fleet": "#7AA116",
    "iot_device_tester": "#7AA116",
    "iot_greengrass_artifact": "#7AA116",
    "iot_greengrass_component": "#7AA116",
    "iot_greengrass_component_machine_learning": "#7AA116",
    "iot_greengrass_component_nucleus": "#7AA116",
    "iot_greengrass_component_private": "#7AA116",
    "iot_greengrass_component_public": "#7AA116",
    "iot_greengrass_interprocess_communication": "#7AA116",
    "iot_greengrass_protocol": "#7AA116",
    "iot_greengrass_recipe": "#7AA116",
    "iot_greengrass_stream_manager": "#7AA116",
    "iot_lorawan_protocol": "#7AA116",
    "iot_over_the_air_update": "#7AA116",
    "iot_sailboat": "#7AA116",
    "iot_sitewise_asset": "#7AA116",
    "iot_sitewise_asset_hierarchy": "#7AA116",
    "iot_sitewise_asset_model": "#7AA116",
    "iot_sitewise_asset_properties": "#7AA116",
    "iot_sitewise_data_streams": "#7AA116",
    "iot_thing_freertos_device": "#7AA116",
    "iot_thing_humidity_sensor": "#7AA116",
    "iot_thing_industrial_pc": "#7AA116",
    "iot_thing_plc": "#7AA116",
    "iot_thing_relay": "#7AA116",
    "iot_thing_stacklight": "#7AA116",
    "iot_thing_temperature_humidity_sensor": "#7AA116",
    "iot_thing_temperature_sensor": "#7AA116",
    "iot_thing_temperature_vibration_sensor": "#7AA116",
    "iot_thing_vibration_sensor": "#7AA116",
    "item": "#C925D1",
    "items": "#C925D1",
    "json_script": "#5A6C86",
    "key_management_service_external_key_store": "#DD344C",
    "lambda_function": "#7AA116",
    "layers": "#E7157B",
    "license_manager_application_discovery": "#E7157B",
    "license_manager_license_blending": "#E7157B",
    "lightbulb": "#7AA116",
    "location_service_geofence": "#DD344C",
    "location_service_map": "#DD344C",
    "location_service_place": "#DD344C",
    "location_service_routes": "#DD344C",
    "location_service_track": "#DD344C",
    "logs": "#E7157B",
    "long_term_security_credential": "#DD344C",
    "m4_instance": "#ED7100",
    "m5_instance": "#ED7100",
    "m5a_instance": "#ED7100",
    "m5d_instance": "#ED7100",
    "m5dn_instance": "#ED7100",
    "m5n_instance": "#ED7100",
    "m5zn_instance": "#ED7100",
    "m6g_instance": "#ED7100",
    "m6gd_instance": "#ED7100",
    "mac_instance": "#ED7100",
    "magnifying_glass_2": "#5A6C86",
    "mainframe_modernization_analyzer": "#01A88D",
    "mainframe_modernization_compiler": "#01A88D",
    "mainframe_modernization_converter": "#01A88D",
    "mainframe_modernization_developer": "#01A88D",
    "mainframe_modernization_runtime": "#01A88D",
    "maintenance_windows": "#E7157B",
    "managed_ms_ad": "#DD344C",
    "management_console2": "#5A6C86",
    "marketplace": "#5A6C86",
    "mediaconnect_gateway": "#ED7100",
    "medical_emergency": "#7AA116",
    "mesh": "#8C4FFF",
    "message": "#E7157B",
    "metrics": "#5A6C86",
    "mfa_token": "#DD344C",
    "migration_hub_refactor_spaces_applications": "#01A88D",
    "migration_hub_refactor_spaces_environments": "#01A88D",
    "migration_hub_refactor_spaces_services": "#01A88D",
    "mobile_client": "#5A6C86",
    "monitoring": "#E7157B",
    "mq_broker": "#E7157B",
    "mqtt_protocol": "#7AA116",
    "msk_amazon_msk_connect": "#8C4FFF",
    "multimedia": "#5A6C86",
    "multiple_volumes_resource": "#7AA116",
    "namespace": "#8C4FFF",
    "nat_gateway": "#8C4FFF",
    "network_access_control_list": "#8C4FFF",
    "network_firewall_endpoints": "#DD344C",
    "network_load_balancer": "#8C4FFF",
    "non_cached_volume": "#7AA116",
    "notebook": "#7AA116",
    "object": "#7AA116",
    "office_building": "#5A6C86",
    "one_zone_ia": "#7AA116",
    "opensearch_dashboards": "#8C4FFF",
    "opensearch_ingestion": "#8C4FFF",
    "opensearch_observability": "#8C4FFF",
    "opensearch_service_cluster_administrator_node": "#8C4FFF",
    "opensearch_service_data_node": "#8C4FFF",
    "opensearch_service_index": "#8C4FFF",
    "opensearch_service_traces": "#8C4FFF",
    "opensearch_service_ultrawarm_node": "#8C4FFF",
    "opsworks_apps": "#E7157B",
    "opsworks_permissions": "#E7157B",
    "optimized_instance": "#ED7100",
    "organizations_account": "#DD344C",
    "organizations_account2": "#E7157B",
    "organizations_management_account": "#E7157B",
    "organizations_management_account2": "#E7157B",
    "organizations_organizational_unit": "#DD344C",
    "organizations_organizational_unit2": "#E7157B",
    "p2_instance": "#ED7100",
    "p3_instance": "#ED7100",
    "p3dn_instance": "#ED7100",
    "p4_instance": "#ED7100",
    "p4d_instance": "#ED7100",
    "parameter_store": "#E7157B",
    "patch_manager": "#E7157B",
    "peering": "#8C4FFF",
    "permissions": "#DD344C",
    "pinpoint_journey": "#DD344C",
    "police_emergency": "#7AA116",
    "policy": "#7AA116",
    "programming_language": "#5A6C86",
    "question": "#5A6C86",
    "queue": "#E7157B",
    "quicksight_paginated_reports": "#8C4FFF",
    "r4_instance": "#ED7100",
    "r5_instance": "#ED7100",
    "r5a_instance": "#ED7100",
    "r5ad_instance": "#ED7100",
    "r5b_instance": "#ED7100",
    "r5d_instance": "#ED7100",
    "r5gd_instance": "#ED7100",
    "r5n_instance": "#ED7100",
    "r6g_instance": "#ED7100",
    "rdn_instance": "#ED7100",
    "rds_blue_green_deployments": "#C925D1",
    "rds_instance": "#C925D1",
    "rds_instance_alt": "#C925D1",
    "rds_mariadb_instance": "#C925D1",
    "rds_mariadb_instance_alt": "#C925D1",
    "rds_multi_az": "#C925D1",
    "rds_multi_az_db_cluster": "#C925D1",
    "rds_mysql_instance": "#C925D1",
    "rds_mysql_instance_alt": "#C925D1",
    "rds_optimized_writes": "#C925D1",
    "rds_oracle_instance": "#C925D1",
    "rds_oracle_instance_alt": "#C925D1",
    "rds_piops": "#C925D1",
    "rds_postgresql_instance": "#C925D1",
    "rds_postgresql_instance_alt": "#C925D1",
    "rds_proxy": "#C925D1",
    "rds_proxy_alt": "#C925D1",
    "rds_sql_server_instance": "#C925D1",
    "rds_sql_server_instance_alt": "#C925D1",
    "rds_trusted_language_extensions_for_postgresql": "#C925D1",
    "recover": "#5A6C86",
    "redshift_auto_copy": "#8C4FFF",
    "redshift_data_sharing_governance": "#8C4FFF",
    "redshift_ml": "#8C4FFF",
    "redshift_query_editor_v20_light": "#8C4FFF",
    "redshift_ra3": "#8C4FFF",
    "redshift_streaming_ingestion": "#8C4FFF",
    "registry": "#ED7100",
    "rekognition_image": "#01A88D",
    "rekognition_video": "#01A88D",
    "replication": "#7AA116",
    "replication_time_control": "#7AA116",
    "reported_state": "#7AA116",
    "rescue": "#ED7100",
    "resource": "#8C4FFF",
    "resources": "#E7157B",
    "role": "#DD344C",
    "route_53_application_recovery_controller": "#8C4FFF",
    "route_53_readiness_checks": "#8C4FFF",
    "route_53_resolver": "#8C4FFF",
    "route_53_resolver_dns_firewall": "#8C4FFF",
    "route_53_resolver_query_logging": "#8C4FFF",
    "route_53_routing_controls": "#8C4FFF",
    "route_table": "#8C4FFF",
    "router": "#8C4FFF",
    "rule": "#7AA116",
    "rule_2": "#E7157B",
    "rule_3": "#E7157B",
    "run_command": "#E7157B",
    "s3_batch_operations": "#7AA116",
    "s3_express_one_zone": "#7AA116",
    "s3_file_gateway": "#7AA116",
    "s3_multi_region_access_points": "#7AA116",
    "s3_object_lambda": "#7AA116",
    "s3_object_lambda_access_points": "#7AA116",
    "s3_object_lock": "#7AA116",
    "s3_on_outposts": "#7AA116",
    "s3_select": "#7AA116",
    "s3_storage_lens": "#7AA116",
    "s3_tables": "#7AA116",
    "s3_vectors": "#7AA116",
    "sagemaker_canvas": "#01A88D",
    "sagemaker_geospatial_ml": "#01A88D",
    "sagemaker_model": "#01A88D",
    "sagemaker_notebook": "#01A88D",
    "sagemaker_shadow_testing": "#01A88D",
    "sagemaker_train": "#01A88D",
    "saml_token": "#5A6C86",
    "search_documents": "#8C4FFF",
    "sensor": "#7AA116",
    "servers": "#5A6C86",
    "service": "#8C4FFF",
    "servo": "#7AA116",
    "shadow": "#7AA116",
    "shield2": "#5A6C86",
    "shield_shield_advanced": "#DD344C",
    "simple_ad": "#DD344C",
    "simple_storage_service_directory_bucket": "#7AA116",
    "simple_storage_service_s3_glacier_instant_retrieval": "#7AA116",
    "simulation": "#DD344C",
    "simulator": "#7AA116",
    "snapshot": "#7AA116",
    "source_code": "#5A6C86",
    "spot_instance": "#ED7100",
    "ssl_padlock": "#5A6C86",
    "stack": "#E7157B",
    "stack2": "#E7157B",
    "standard_ia": "#7AA116",
    "state_manager": "#E7157B",
    "streaming_distribution": "#8C4FFF",
    "sts": "#DD344C",
    "sts_alternate": "#DD344C",
    "systems_manager_application_manager": "#E7157B",
    "systems_manager_change_calendar": "#E7157B",
    "systems_manager_change_manager": "#E7157B",
    "systems_manager_compliance": "#E7157B",
    "systems_manager_distributor": "#E7157B",
    "systems_manager_incident_manager": "#E7157B",
    "systems_manager_opscenter": "#E7157B",
    "systems_manager_session_manager": "#E7157B",
    "t2_instance": "#ED7100",
    "t3_instance": "#ED7100",
    "t3a_instance": "#ED7100",
    "t4g_instance": "#ED7100",
    "table": "#C925D1",
    "tape_gateway": "#7AA116",
    "tape_storage": "#5A6C86",
    "template": "#E7157B",
    "temporary_security_credential": "#DD344C",
    "textract_analyze_lending": "#01A88D",
    "thermostat": "#7AA116",
    "topic": "#E7157B",
    "topic_2": "#7AA116",
    "traditional_server": "#5A6C86",
    "trainium_instance": "#ED7100",
    "transfer_family_aws_as2": "#01A88D",
    "transfer_for_ftp_resource": "#01A88D",
    "transfer_for_ftps_resource": "#01A88D",
    "transfer_for_sftp_resource": "#01A88D",
    "transit_gateway_attachment": "#8C4FFF",
    "travel": "#7AA116",
    "user": "#5A6C86",
    "users": "#232F3D",
    "utility": "#7AA116",
    "vault": "#7AA116",
    "virtual_gateway": "#8C4FFF",
    "virtual_node": "#8C4FFF",
    "virtual_router": "#8C4FFF",
    "virtual_service": "#8C4FFF",
    "virtual_tape_library": "#7AA116",
    "volume": "#7AA116",
    "volume_gateway": "#7AA116",
    "vpc_access_points": "#7AA116",
    "vpc_carrier_gateway": "#8C4FFF",
    "vpc_network_access_analyzer": "#8C4FFF",
    "vpc_reachability_analyzer": "#8C4FFF",
    "vpc_traffic_mirroring": "#8C4FFF",
    "vpc_virtual_private_cloud_vpc": "#8C4FFF",
    "vpn_connection": "#8C4FFF",
    "vpn_gateway": "#8C4FFF",
    "waf_bad_bot": "#DD344C",
    "waf_bot": "#DD344C",
    "waf_bot_control": "#DD344C",
    "waf_labels": "#DD344C",
    "waf_managed_rule": "#DD344C",
    "waf_rule": "#DD344C",
    "windfarm": "#7AA116",
    "workspaces_family_amazon_workspaces": "#01A88D",
    "workspaces_family_amazon_workspaces_core": "#01A88D",
    "workspaces_workspaces_web": "#01A88D",
    "x1_instance2": "#ED7100",
    "x1e_instance": "#ED7100",
    "z1d_instance": "#ED7100",
}
