"""Unit tests for the drawio emitter module."""

import json
import xml.etree.ElementTree as ET

import pytest

from modules.drawio_emitter import (
    emit_drawio,
    load_shape_map,
    _sanitize_label,
    _topo_sort_clusters,
    _node_inside_cluster,
)
from modules.xdot_parser import XdotGraph, XdotNode, XdotCluster, XdotEdge


# ── Fixtures ──────────────────────────────────────────────────────────


def _simple_graph():
    """Build a minimal XdotGraph with one node."""
    g = XdotGraph(bounding_box=(0, 0, 500, 400))
    g.nodes["aws_lambda.func"] = XdotNode(
        id="aws_lambda.func",
        pos=(250, 200),
        width=1.0,
        height=1.0,
        label="func",
    )
    return g


def _graph_with_cluster():
    """Build a graph with one cluster containing one node."""
    g = XdotGraph(bounding_box=(0, 0, 600, 500))
    g.clusters["cluster_VPCgroup.1"] = XdotCluster(
        name="cluster_VPCgroup.1",
        bb=(50, 50, 500, 400),
        label="VPC",
        style={"fillcolor": "#E5F5FD", "color": "#2196F3"},
    )
    g.nodes["aws_instance.web"] = XdotNode(
        id="aws_instance.web",
        pos=(250, 200),
        width=1.0,
        height=1.0,
        label="web",
    )
    return g


def _graph_with_edges():
    """Build a graph with two nodes and an edge."""
    g = XdotGraph(bounding_box=(0, 0, 600, 400))
    g.nodes["src"] = XdotNode(
        id="src", pos=(100, 200), width=1.0, height=1.0, label="source"
    )
    g.nodes["dst"] = XdotNode(
        id="dst", pos=(400, 200), width=1.0, height=1.0, label="dest"
    )
    g.edges.append(XdotEdge(source="src", target="dst"))
    return g


def _graph_with_special_nodes():
    """Build a graph with title, footer, legend nodes."""
    g = XdotGraph(bounding_box=(0, 0, 800, 600))
    g.nodes["title"] = XdotNode(
        id="title",
        pos=(400, 580),
        width=5.0,
        height=0.5,
        label="My Architecture",
        attrs={"_titlenode": "1"},
    )
    g.nodes["footer"] = XdotNode(
        id="footer",
        pos=(400, 20),
        width=5.0,
        height=1.0,
        label="Generated by TerraVision",
        attrs={"_footernode": "1"},
    )
    g.nodes["legend"] = XdotNode(
        id="legend",
        pos=(600, 20),
        width=3.0,
        height=2.0,
        label="Flow Legend",
        attrs={"_legendnode": "1"},
    )
    return g


# ── Helpers ───────────────────────────────────────────────────────────


def _parse_model(xml_str):
    """Parse emitter output and return the mxGraphModel element."""
    mxfile = ET.fromstring(xml_str)
    return mxfile.find(".//mxGraphModel")


# ── Tests ─────────────────────────────────────────────────────────────


class TestEmitDrawioValidXML:
    def test_produces_valid_xml(self):
        xml = emit_drawio(_simple_graph(), {}, set(), {}, {})
        root = ET.fromstring(xml)
        assert root.tag == "mxfile"
        diagram = root.find("diagram")
        assert diagram is not None
        model = diagram.find("mxGraphModel")
        assert model is not None

    def test_root_cells_present(self):
        xml = emit_drawio(_simple_graph(), {}, set(), {}, {})
        root = _parse_model(xml)
        cells = root.findall(".//mxCell")
        ids = {c.get("id") for c in cells}
        assert "0" in ids
        assert "1" in ids

    def test_node_count_matches(self):
        g = _simple_graph()
        g.nodes["node2"] = XdotNode(
            id="node2", pos=(300, 300), width=1.0, height=1.0, label="node2"
        )
        xml = emit_drawio(g, {}, set(), {}, {})
        root = _parse_model(xml)
        vertices = [c for c in root.findall(".//mxCell") if c.get("vertex") == "1"]
        assert len(vertices) == 2  # Two resource nodes


class TestCoordinateTransformation:
    def test_y_flip(self):
        """Node at Graphviz y=300 in a graph height=400 should be at drawio y≈100."""
        g = XdotGraph(bounding_box=(0, 0, 500, 400))
        g.nodes["n"] = XdotNode(
            id="n", pos=(250, 300), width=1.0, height=1.0, label="n"
        )
        xml = emit_drawio(g, {}, set(), {}, {})
        root = _parse_model(xml)
        node_cell = [
            c
            for c in root.findall(".//mxCell")
            if c.get("vertex") == "1" and c.get("value") == "n"
        ]
        assert len(node_cell) == 1
        geo = node_cell[0].find("mxGeometry")
        y = float(geo.get("y"))
        # Graphviz y=300, graph_height=400, flipped = 400-300=100, minus half height
        assert y < 200  # Should be near top of canvas


class TestClusterRendering:
    def test_cluster_cell_created(self):
        xml = emit_drawio(_graph_with_cluster(), {}, set(), {}, {})
        root = _parse_model(xml)
        cells = root.findall(".//mxCell")
        cluster_cells = [
            c
            for c in cells
            if c.get("vertex") == "1" and "container=1" in (c.get("style") or "")
        ]
        assert len(cluster_cells) == 1

    def test_nested_cluster_parent(self):
        g = XdotGraph(bounding_box=(0, 0, 800, 600))
        g.clusters["cluster_outer"] = XdotCluster(
            name="cluster_outer", bb=(10, 10, 700, 500), label="Outer"
        )
        g.clusters["cluster_inner"] = XdotCluster(
            name="cluster_inner",
            bb=(50, 50, 400, 300),
            label="Inner",
            parent="cluster_outer",
        )
        xml = emit_drawio(g, {}, set(), {}, {})
        root = _parse_model(xml)
        cells = {c.get("value"): c for c in root.findall(".//mxCell")}
        inner = cells.get("Inner")
        outer = cells.get("Outer")
        assert inner is not None
        assert outer is not None
        assert inner.get("parent") == outer.get("id")


class TestEdgeRendering:
    def test_edge_created(self):
        xml = emit_drawio(_graph_with_edges(), {}, set(), {}, {})
        root = _parse_model(xml)
        edges = [c for c in root.findall(".//mxCell") if c.get("edge") == "1"]
        assert len(edges) == 1

    def test_edge_source_target(self):
        xml = emit_drawio(_graph_with_edges(), {}, set(), {}, {})
        root = _parse_model(xml)
        edges = [c for c in root.findall(".//mxCell") if c.get("edge") == "1"]
        edge = edges[0]
        assert edge.get("source") is not None
        assert edge.get("target") is not None
        assert edge.get("source") != edge.get("target")

    def test_bidirectional_edge(self):
        g = _graph_with_edges()
        g.edges[0] = XdotEdge(source="src", target="dst", is_bidirectional=True)
        xml = emit_drawio(g, {}, set(), {}, {})
        root = _parse_model(xml)
        edges = [c for c in root.findall(".//mxCell") if c.get("edge") == "1"]
        style = edges[0].get("style")
        assert "startArrow=classic" in style


class TestNativeShapeStyle:
    def test_native_shape_used(self):
        shape_map = {"aws_lambda_function": "mxgraph.aws4.lambda_function"}
        g = _simple_graph()
        node_id_map = {"aws_lambda.func": "aws_lambda_function.my_func"}
        xml = emit_drawio(g, shape_map, set(), node_id_map, {})
        root = _parse_model(xml)
        cells = root.findall(".//mxCell")
        node_cell = [
            c for c in cells if c.get("vertex") == "1" and c.get("value") == "func"
        ]
        assert len(node_cell) == 1
        style = node_cell[0].get("style")
        assert "mxgraph.aws4.lambda_function" in style

    def test_fallback_when_no_mapping(self):
        """Unmapped resource type gets a default style, not a native shape."""
        g = _simple_graph()
        xml = emit_drawio(g, {}, set(), {}, {})
        root = _parse_model(xml)
        cells = root.findall(".//mxCell")
        node_cell = [
            c for c in cells if c.get("vertex") == "1" and c.get("value") == "func"
        ]
        style = node_cell[0].get("style")
        assert "mxgraph." not in style


class TestSpecialNodes:
    def test_title_footer_legend_at_root(self):
        xml = emit_drawio(_graph_with_special_nodes(), {}, set(), {}, {})
        root = _parse_model(xml)
        cells = root.findall(".//mxCell")
        special = [
            c
            for c in cells
            if c.get("value")
            in ("My Architecture", "Generated by TerraVision", "Flow Legend")
        ]
        for cell in special:
            assert cell.get("parent") == "1"

    def test_title_style(self):
        xml = emit_drawio(_graph_with_special_nodes(), {}, set(), {}, {})
        root = _parse_model(xml)
        cells = root.findall(".//mxCell")
        title = [c for c in cells if c.get("value") == "My Architecture"][0]
        assert "fontSize=28" in title.get("style")
        assert "fontStyle=1" in title.get("style")


class TestLabelSanitization:
    def test_plain_text(self):
        assert _sanitize_label("Hello World") == "Hello World"

    def test_xml_escaping(self):
        result = _sanitize_label('A < B & C > D "E"')
        assert "&lt;" in result
        assert "&amp;" in result
        assert "&gt;" in result
        assert "&quot;" in result

    def test_html_table_text_extracted(self):
        html = "<TABLE><TR><TD>Hello</TD></TR></TABLE>"
        result = _sanitize_label(f"<{html}>")
        assert result == "Hello"

    def test_empty_label(self):
        assert _sanitize_label("") == ""
        assert _sanitize_label(None) == ""


class TestLoadShapeMap:
    def test_aws_map_loads(self):
        m = load_shape_map("aws")
        assert len(m) > 50
        assert "aws_lambda_function" in m

    def test_azure_map_loads(self):
        m = load_shape_map("azure")
        assert len(m) > 30

    def test_gcp_map_loads(self):
        m = load_shape_map("gcp")
        assert len(m) > 20

    def test_unknown_provider_returns_empty(self):
        m = load_shape_map("nonexistent_provider")
        assert m == {}

    def test_shape_names_follow_convention(self):
        """Shape names must use draw.io conventions per provider."""
        for provider in ("aws", "azure", "gcp"):
            m = load_shape_map(provider)
            for resource_type, shape_name in m.items():
                valid = shape_name.startswith("mxgraph.") or shape_name.startswith(
                    "img/lib/"
                )
                assert valid, (
                    f"{provider}/{resource_type}: {shape_name} "
                    "doesn't start with mxgraph. or img/lib/"
                )

    def test_no_duplicate_mappings(self):
        """No two resource types should map to the same shape."""
        for provider in ("aws", "azure", "gcp"):
            m = load_shape_map(provider)
            values = list(m.values())
            # Allow duplicates for variants (e.g., aws_alb and aws_lb_alb can map to same shape)
            # Just check there's no identical key
            assert len(m.keys()) == len(set(m.keys()))


class TestTopoSortClusters:
    def test_parent_before_child(self):
        clusters = {
            "cluster_child": XdotCluster(
                name="cluster_child", bb=(0, 0, 100, 100), parent="cluster_parent"
            ),
            "cluster_parent": XdotCluster(name="cluster_parent", bb=(0, 0, 200, 200)),
        }
        order = _topo_sort_clusters(clusters)
        assert order.index("cluster_parent") < order.index("cluster_child")


class TestNodeInsideCluster:
    def test_inside(self):
        node = XdotNode(id="n", pos=(100, 100), width=1, height=1)
        cluster = XdotCluster(name="c", bb=(50, 50, 200, 200))
        assert _node_inside_cluster(node, cluster) is True

    def test_outside(self):
        node = XdotNode(id="n", pos=(300, 300), width=1, height=1)
        cluster = XdotCluster(name="c", bb=(50, 50, 200, 200))
        assert _node_inside_cluster(node, cluster) is False
