#!/usr/bin/env python3
"""Auto-generate draw.io shape mapping files from authoritative sources.

Downloads the latest shape definitions from the jgraph/drawio GitHub
repository and matches them against TerraVision resource class aliases
to produce ``modules/config/drawio_shape_map_<provider>.py`` files.

Usage::

    poetry run python scripts/generate_drawio_shape_maps.py

Re-run whenever draw.io updates their icon libraries (check releases at
https://github.com/jgraph/drawio/releases).

Shape library sources (jgraph/drawio repo):
  - AWS:   Sidebar-AWS4.js  → prefix ``mxgraph.aws4.``  (stencil shapes)
  - Azure: img/lib/azure2/  → SVG image paths (NOT stencils)
  - GCP:   Not generated — uses base64-embedded local PNGs at runtime
"""

import importlib
import json
import pkgutil
import re
import sys
import urllib.request
from pathlib import Path
from typing import Dict, List

# Ensure repo root is on sys.path so we can import resource_classes
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

DRAWIO_REPO = "jgraph/drawio"
DRAWIO_BRANCH = "dev"  # tracks latest; pin to a tag for stability
RAW_BASE = (
    f"https://raw.githubusercontent.com/{DRAWIO_REPO}/{DRAWIO_BRANCH}"
    "/src/main/webapp"
)
SIDEBAR_AWS4_URL = f"{RAW_BASE}/js/diagramly/sidebar/Sidebar-AWS4.js"
IMG_LIB_API = (
    f"https://api.github.com/repos/{DRAWIO_REPO}/contents"
    f"/src/main/webapp/img/lib/azure2?ref={DRAWIO_BRANCH}"
)

OUTPUT_DIR = REPO_ROOT / "modules" / "config"


# ── Fetch helpers ─────────────────────────────────────────────────────


def fetch_sidebar_aws4_shapes() -> List[str]:
    """Fetch Sidebar-AWS4.js and extract all shape names.

    The sidebar JS is the authoritative source for shape names — it uses
    underscores where the stencil XML uses spaces, and includes shapes
    not in the stencil XML.
    """
    print(f"  Fetching {SIDEBAR_AWS4_URL} ...")
    with urllib.request.urlopen(SIDEBAR_AWS4_URL) as resp:
        js_text = resp.read().decode("utf-8")

    # Extract shape names from patterns like:
    #   n + 'instance2;'           → direct shape
    #   n2 + 'resIcon=...ec2;'     → resourceIcon shape
    #   shape=mxgraph.aws4.<name>  → any shape reference
    shapes = set()

    # Direct shapes: n + '<name>;'
    for m in re.finditer(r"n\s*\+\s*'([^']+);'", js_text):
        name = m.group(1)
        if "=" not in name:  # Skip style properties
            shapes.add(name)

    # resourceIcon shapes: resIcon=mxgraph.aws4.<name>;
    for m in re.finditer(r"resIcon=mxgraph\.aws4\.([^;'\"]+)", js_text):
        shapes.add(m.group(1))

    # General shape references: shape=mxgraph.aws4.<name>
    for m in re.finditer(r"shape=mxgraph\.aws4\.([^;'\"]+)", js_text):
        name = m.group(1)
        if name not in ("group", "groupCenter", "resourceIcon"):
            shapes.add(name)

    print(f"  Extracted {len(shapes)} shapes from Sidebar-AWS4.js")
    return sorted(shapes)


def fetch_azure2_svgs() -> Dict[str, List[str]]:
    """Fetch Azure2 SVG icon paths grouped by category.

    Falls back to a local cache file if the GitHub API is rate-limited.
    """
    # Try local cache first (generated by earlier run)
    cache_path = (
        REPO_ROOT / "specs" / "012-native-drawio-emitter" / "azure2-svgs-reference.txt"
    )
    if cache_path.exists():
        print(f"  Loading Azure2 SVGs from local cache: {cache_path}")
        result: Dict[str, List[str]] = {}
        for line in cache_path.read_text().splitlines():
            line = line.strip()
            if not line or not line.startswith("img/lib/azure2/"):
                continue
            parts = line.split("/")
            if len(parts) >= 5:
                cat = parts[3]
                result.setdefault(cat, []).append(line)
        return result

    result = {}
    print(f"  Fetching Azure2 SVG listing from GitHub API ...")
    with urllib.request.urlopen(IMG_LIB_API) as resp:
        categories = json.loads(resp.read().decode("utf-8"))

    for cat in categories:
        if cat["type"] != "dir":
            continue
        cat_name = cat["name"]
        cat_url = cat["url"]
        try:
            with urllib.request.urlopen(cat_url) as resp2:
                files = json.loads(resp2.read().decode("utf-8"))
            svgs = [
                f"img/lib/azure2/{cat_name}/{f['name']}"
                for f in files
                if f["name"].endswith(".svg")
            ]
            result[cat_name] = svgs
        except Exception:
            pass
    return result


# ── Resource class discovery ──────────────────────────────────────────


def discover_resource_aliases(provider_package: str) -> Dict[str, str]:
    """Import a provider's resource_classes package and collect aliases.

    Returns dict mapping alias name (e.g. 'aws_lambda_function') to
    the Python class name (e.g. 'Lambda').
    """
    pkg_path = REPO_ROOT / "resource_classes" / provider_package
    if not pkg_path.exists():
        return {}

    aliases = {}
    pkg = importlib.import_module(f"resource_classes.{provider_package}")

    for _importer, modname, _ispkg in pkgutil.iter_modules(pkg.__path__):
        try:
            mod = importlib.import_module(
                f"resource_classes.{provider_package}.{modname}"
            )
        except Exception:
            continue
        for attr_name in dir(mod):
            if attr_name.startswith("_"):
                continue
            obj = getattr(mod, attr_name)
            if isinstance(obj, type) and attr_name != obj.__name__:
                # This is an alias: `aws_lambda_function = Lambda`
                aliases[attr_name] = obj.__name__
    return aliases


# ── Matching logic ────────────────────────────────────────────────────


def _normalize(name: str) -> str:
    """Normalize a name for fuzzy matching: lowercase, strip non-alnum."""
    return re.sub(r"[^a-z0-9]", "", name.lower())


# Manual overrides for services where auto-matching fails.
# These are verified against the authoritative source files.
AWS_OVERRIDES = {
    "aws_subnet": "mxgraph.aws4.subnet",
    "aws_security_group": "mxgraph.aws4.security group",
    "aws_autoscaling_group": "mxgraph.aws4.auto scaling2",
    "aws_appautoscaling_target": "mxgraph.aws4.application auto scaling",
    "aws_lb": "mxgraph.aws4.elastic load balancing",
    "aws_alb": "mxgraph.aws4.application load balancer",
    "aws_nlb": "mxgraph.aws4.network load balancer",
    "aws_elb": "mxgraph.aws4.classic load balancer",
    "aws_lb_alb": "mxgraph.aws4.application load balancer",
    "aws_lb_nlb": "mxgraph.aws4.network load balancer",
    "aws_instance": "mxgraph.aws4.ec2",
    "aws_lambda_function": "mxgraph.aws4.lambda function",
    "aws_s3_bucket": "mxgraph.aws4.s3",
    "aws_dynamodb_table": "mxgraph.aws4.dynamodb",
    "aws_sqs_queue": "mxgraph.aws4.sqs",
    "aws_sns_topic": "mxgraph.aws4.sns",
    "aws_rds_cluster": "mxgraph.aws4.rds",
    "aws_db_instance": "mxgraph.aws4.rds instance",
    "aws_ecs_service": "mxgraph.aws4.ecs service",
    "aws_ecs_cluster": "mxgraph.aws4.ecs",
    "aws_eks_cluster": "mxgraph.aws4.eks",
    "aws_fargate": "mxgraph.aws4.fargate",
    "aws_cloudfront_distribution": "mxgraph.aws4.cloudfront",
    "aws_route53_zone": "mxgraph.aws4.route 53",
    "aws_route53_record": "mxgraph.aws4.route 53",
    "aws_api_gateway_rest_api": "mxgraph.aws4.api gateway",
    "aws_apigatewayv2_api": "mxgraph.aws4.api gateway",
    "aws_cognito_user_pool": "mxgraph.aws4.cognito",
    "aws_wafv2_web_acl": "mxgraph.aws4.waf",
    "aws_waf_web_acl": "mxgraph.aws4.waf",
    "aws_sfn_state_machine": "mxgraph.aws4.step functions",
    "aws_kinesis_stream": "mxgraph.aws4.kinesis",
    "aws_kinesis_firehose_delivery_stream": "mxgraph.aws4.kinesis data firehose",
    "aws_cloudwatch_metric_alarm": "mxgraph.aws4.cloudwatch",
    "aws_cloudwatch_log_group": "mxgraph.aws4.cloudwatch logs",
    "aws_iam_role": "mxgraph.aws4.role",
    "aws_iam_policy": "mxgraph.aws4.identity_and_access_management",
    "aws_iam_group": "mxgraph.aws4.identity_and_access_management",
    "aws_iam_user": "mxgraph.aws4.identity_and_access_management",
    "aws_iam_policy_attachment": "mxgraph.aws4.identity_and_access_management",
    "aws_iam_role_policy": "mxgraph.aws4.role",
    "aws_iam_role_policy_attachment": "mxgraph.aws4.role",
    "aws_iam_instance_profile": "mxgraph.aws4.role",
    "aws_kms_key": "mxgraph.aws4.kms",
    "aws_secretsmanager_secret": "mxgraph.aws4.secrets manager",
    "aws_elasticache_cluster": "mxgraph.aws4.elasticache",
    "aws_elasticache_replication_group": "mxgraph.aws4.elasticache for redis",
    "aws_redshift_cluster": "mxgraph.aws4.redshift",
    "aws_glue_job": "mxgraph.aws4.glue",
    "aws_glue_catalog_database": "mxgraph.aws4.glue data catalog",
    "aws_sagemaker_endpoint": "mxgraph.aws4.sagemaker",
    "aws_sagemaker_notebook_instance": "mxgraph.aws4.sagemaker notebook",
    "aws_eventbridge_rule": "mxgraph.aws4.eventbridge",
    "aws_cloudwatch_event_rule": "mxgraph.aws4.eventbridge",
    "aws_ebs_volume": "mxgraph.aws4.elastic block store",
    "aws_efs_file_system": "mxgraph.aws4.elastic file system",
    "aws_ecr_repository": "mxgraph.aws4.elastic container registry",
    "aws_codecommit_repository": "mxgraph.aws4.codecommit",
    "aws_codebuild_project": "mxgraph.aws4.codebuild",
    "aws_codepipeline": "mxgraph.aws4.codepipeline",
    "aws_codedeploy_app": "mxgraph.aws4.codedeploy",
    "aws_transfer_server": "mxgraph.aws4.transfer family",
    "aws_acm_certificate": "mxgraph.aws4.certificate manager",
    "aws_ses_domain_identity": "mxgraph.aws4.simple email service",
    "aws_msk_cluster": "mxgraph.aws4.managed streaming for apache kafka",
    "aws_mq_broker": "mxgraph.aws4.mq",
    "aws_backup_plan": "mxgraph.aws4.backup",
    "aws_eip": "mxgraph.aws4.elastic ip address",
    "aws_network_acl": "mxgraph.aws4.network access control list",
    "aws_network_interface": "mxgraph.aws4.elastic network interface",
    "aws_ssm_parameter": "mxgraph.aws4.systems manager parameter store",
    "aws_ssm_document": "mxgraph.aws4.systems manager documents",
    "aws_dms_endpoint": "mxgraph.aws4.database migration service",
    "aws_dx_connection": "mxgraph.aws4.direct connect",
    "aws_dx_gateway": "mxgraph.aws4.direct connect gateway",
    "aws_ebs_snapshot": "mxgraph.aws4.elastic block store snapshot",
    "aws_launch_template": "mxgraph.aws4.ec2",
    "aws_lb_listener": "mxgraph.aws4.elastic load balancing",
    "aws_lb_target_group": "mxgraph.aws4.elastic load balancing",
    "aws_scheduler_schedule": "mxgraph.aws4.eventbridge scheduler",
    "aws_egress_only_internet_gateway": "mxgraph.aws4.internet gateway",
    "aws_ce_cost_category": "mxgraph.aws4.cost explorer",
    "aws_cur_report_definition": "mxgraph.aws4.cost and usage report",
}

# Azure maps to img/lib/azure2/ SVG paths, NOT stencil names.
AZURE_OVERRIDES = {
    "azurerm_api_management": "img/lib/azure2/integration/API_Management_Services.svg",
    "azurerm_app_service": "img/lib/azure2/compute/App_Services.svg",
    "azurerm_application_gateway": "img/lib/azure2/networking/Application_Gateways.svg",
    "azurerm_application_insights": "img/lib/azure2/devops/Application_Insights.svg",
    "azurerm_automation_account": "img/lib/azure2/management_governance/Automation_Accounts.svg",
    "azurerm_availability_set": "img/lib/azure2/compute/Availability_Sets.svg",
    "azurerm_cdn_endpoint": "img/lib/azure2/networking/CDN_Profiles.svg",
    "azurerm_container_group": "img/lib/azure2/compute/Container_Instances.svg",
    "azurerm_container_registry": "img/lib/azure2/containers/Container_Registries.svg",
    "azurerm_cosmosdb_account": "img/lib/azure2/databases/Azure_Cosmos_DB.svg",
    "azurerm_data_factory": "img/lib/azure2/databases/Data_Factory.svg",
    "azurerm_dns_zone": "img/lib/azure2/networking/DNS_Zones.svg",
    "azurerm_eventhub_namespace": "img/lib/azure2/analytics/Event_Hubs.svg",
    "azurerm_express_route_circuit": "img/lib/azure2/networking/ExpressRoute_Circuits.svg",
    "azurerm_firewall": "img/lib/azure2/networking/Firewalls.svg",
    "azurerm_frontdoor": "img/lib/azure2/networking/Front_Doors.svg",
    "azurerm_function_app": "img/lib/azure2/compute/Function_Apps.svg",
    "azurerm_iothub": "img/lib/azure2/iot/IoT_Hub.svg",
    "azurerm_key_vault": "img/lib/azure2/security/Key_Vaults.svg",
    "azurerm_kubernetes_cluster": "img/lib/azure2/compute/Kubernetes_Services.svg",
    "azurerm_lb": "img/lib/azure2/networking/Load_Balancers.svg",
    "azurerm_linux_function_app": "img/lib/azure2/compute/Function_Apps.svg",
    "azurerm_linux_virtual_machine": "img/lib/azure2/compute/Virtual_Machine.svg",
    "azurerm_linux_web_app": "img/lib/azure2/compute/App_Services.svg",
    "azurerm_log_analytics_workspace": "img/lib/azure2/analytics/Log_Analytics_Workspaces.svg",
    "azurerm_logic_app_workflow": "img/lib/azure2/integration/Logic_Apps.svg",
    "azurerm_managed_disk": "img/lib/azure2/compute/Disks.svg",
    "azurerm_monitor_action_group": "img/lib/azure2/management_governance/Monitor.svg",
    "azurerm_mssql_database": "img/lib/azure2/databases/SQL_Database.svg",
    "azurerm_mssql_server": "img/lib/azure2/databases/SQL_Server.svg",
    "azurerm_mysql_flexible_server": "img/lib/azure2/databases/Azure_Database_MySQL_Server.svg",
    "azurerm_mysql_server": "img/lib/azure2/databases/Azure_Database_MySQL_Server.svg",
    "azurerm_network_interface": "img/lib/azure2/networking/Network_Interfaces.svg",
    "azurerm_network_security_group": "img/lib/azure2/networking/Network_Security_Groups.svg",
    "azurerm_postgresql_flexible_server": "img/lib/azure2/databases/Azure_Database_PostgreSQL_Server.svg",
    "azurerm_postgresql_server": "img/lib/azure2/databases/Azure_Database_PostgreSQL_Server.svg",
    "azurerm_private_dns_zone": "img/lib/azure2/networking/Private_DNS_Zones.svg",
    "azurerm_private_endpoint": "img/lib/azure2/networking/Private_Endpoints.svg",
    "azurerm_public_ip": "img/lib/azure2/networking/Public_IP_Addresses.svg",
    "azurerm_recovery_services_vault": "img/lib/azure2/management_governance/Recovery_Services_Vaults.svg",
    "azurerm_redis_cache": "img/lib/azure2/databases/Cache_Redis.svg",
    "azurerm_resource_group": "img/lib/azure2/general/Resource_Groups.svg",
    "azurerm_route_table": "img/lib/azure2/networking/Route_Tables.svg",
    "azurerm_service_fabric_cluster": "img/lib/azure2/compute/Service_Fabric_Clusters.svg",
    "azurerm_servicebus_namespace": "img/lib/azure2/integration/Service_Bus.svg",
    "azurerm_sql_server": "img/lib/azure2/databases/SQL_Server.svg",
    "azurerm_storage_account": "img/lib/azure2/storage/Storage_Accounts.svg",
    "azurerm_subnet": "img/lib/azure2/networking/Subnets.svg",
    "azurerm_traffic_manager_profile": "img/lib/azure2/networking/Traffic_Manager_Profiles.svg",
    "azurerm_virtual_machine": "img/lib/azure2/compute/Virtual_Machine.svg",
    "azurerm_virtual_machine_scale_set": "img/lib/azure2/compute/VM_Scale_Sets.svg",
    "azurerm_virtual_network": "img/lib/azure2/networking/Virtual_Networks.svg",
    "azurerm_virtual_network_gateway": "img/lib/azure2/networking/Virtual_Network_Gateways.svg",
    "azurerm_windows_function_app": "img/lib/azure2/compute/Function_Apps.svg",
    "azurerm_windows_virtual_machine": "img/lib/azure2/compute/Virtual_Machine.svg",
    "azurerm_windows_web_app": "img/lib/azure2/compute/App_Services.svg",
    "tv_azurerm_internet": "img/lib/azure2/general/Globe.svg",
    "azurerm_role_assignment": "img/lib/azure2/identity/Managed_Identities.svg",
    "azurerm_role_definition": "img/lib/azure2/identity/Managed_Identities.svg",
    "azurerm_user_assigned_identity": "img/lib/azure2/identity/Managed_Identities.svg",
    "tv_azurerm_users": "img/lib/azure2/identity/Users.svg",
}


def match_aws(aliases: Dict[str, str], shapes: List[str]) -> Dict[str, str]:
    """Match AWS resource aliases to aws4 stencil shape names."""
    matched = {k: v for k, v in AWS_OVERRIDES.items() if k in aliases}

    shape_lookup = {_normalize(s): s for s in shapes}

    for alias in sorted(aliases.keys()):
        if alias in matched:
            continue
        suffix = alias
        for prefix in ("aws_", "tv_aws_"):
            if alias.startswith(prefix):
                suffix = alias[len(prefix) :]
                break

        norm = _normalize(suffix)
        if norm in shape_lookup:
            matched[alias] = f"mxgraph.aws4.{shape_lookup[norm]}"
            continue

        candidates = [
            suffix,
            suffix.replace("_", " "),
            suffix.replace("_function", ""),
            suffix.replace("_cluster", ""),
            suffix.replace("_instance", ""),
        ]
        found = False
        for cand in candidates:
            cn = _normalize(cand)
            if cn in shape_lookup:
                matched[alias] = f"mxgraph.aws4.{shape_lookup[cn]}"
                found = True
                break
        if found:
            continue

        parts = suffix.split("_")
        for i in range(len(parts), 0, -1):
            partial = _normalize("".join(parts[:i]))
            if partial in shape_lookup:
                matched[alias] = f"mxgraph.aws4.{shape_lookup[partial]}"
                break

    return matched


def match_azure(
    aliases: Dict[str, str], azure2_svgs: Dict[str, List[str]]
) -> Dict[str, str]:
    """Match Azure resource aliases to img/lib/azure2/ SVG paths."""
    # Apply overrides first
    matched = {k: v for k, v in AZURE_OVERRIDES.items() if k in aliases}

    # Build lookup: normalized SVG basename (without extension) -> full path
    svg_lookup: Dict[str, str] = {}
    for cat, paths in azure2_svgs.items():
        for path in paths:
            basename = path.rsplit("/", 1)[-1].replace(".svg", "")
            norm = _normalize(basename)
            svg_lookup[norm] = path

    for alias in sorted(aliases.keys()):
        if alias in matched:
            continue
        suffix = alias
        for prefix in ("azurerm_", "azuread_", "tv_azure_", "tv_azurerm_"):
            if alias.startswith(prefix):
                suffix = alias[len(prefix) :]
                break

        # Try normalized suffix against SVG basenames
        norm = _normalize(suffix)
        if norm in svg_lookup:
            matched[alias] = svg_lookup[norm]
            continue

        # Try common transformations
        candidates = [
            suffix.replace("_", ""),
            suffix.replace("_", " "),
            suffix.replace("_group", "").replace("_", ""),
            suffix.replace("_cluster", "").replace("_", ""),
            suffix.replace("_server", "").replace("_", ""),
        ]
        found = False
        for cand in candidates:
            cn = _normalize(cand)
            if cn in svg_lookup:
                matched[alias] = svg_lookup[cn]
                found = True
                break

    return matched


# ── Code generation ───────────────────────────────────────────────────


def write_map_file(
    provider: str,
    var_name: str,
    mapping: Dict[str, str],
    note: str,
):
    """Write a shape map Python file."""
    out_path = OUTPUT_DIR / f"drawio_shape_map_{provider}.py"

    # Determine style description based on provider
    if provider == "azure":
        style_desc = (
            "Uses img/lib/azure2/ SVG image paths from draw.io.\n"
            "Style: image;aspect=fixed;html=1;points=[];align=center;fontSize=12;image=<path>;"
        )
    else:
        style_desc = (
            f"Maps terraform resource types to mxgraph.{provider}4.* stencil shapes."
        )

    lines = [
        f'"""draw.io shape mapping for {provider.upper()} resource types.',
        "",
        f"Auto-generated by scripts/generate_drawio_shape_maps.py",
        f"Source: {note}",
        f"Total mappings: {len(mapping)}",
        "",
        style_desc,
        '"""',
        "",
        f"{var_name} = {{",
    ]
    for alias, shape in sorted(mapping.items()):
        lines.append(f'    "{alias}": "{shape}",')
    lines.append("}")
    lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"  Wrote {out_path} ({len(mapping)} mappings)")


# ── Main ──────────────────────────────────────────────────────────────


def main():
    print("=== Discovering TerraVision resource class aliases ===")
    aws_aliases = discover_resource_aliases("aws")
    azure_aliases = discover_resource_aliases("azure")
    print(f"  AWS: {len(aws_aliases)} aliases")
    print(f"  Azure: {len(azure_aliases)} aliases")
    print(f"  GCP: skipped (uses base64-embedded local PNGs)")

    print("\n=== Fetching draw.io shape libraries ===")
    aws4_shapes = fetch_sidebar_aws4_shapes()
    print(f"  AWS4 shapes: {len(aws4_shapes)}")

    azure2_svgs = fetch_azure2_svgs()
    total_azure_svgs = sum(len(v) for v in azure2_svgs.values())
    print(f"  Azure2 SVGs: {total_azure_svgs} across {len(azure2_svgs)} categories")

    print("\n=== Matching resource types to shapes ===")
    aws_map = match_aws(aws_aliases, aws4_shapes)
    print(
        f"  AWS: {len(aws_map)}/{len(aws_aliases)} matched "
        f"({len(aws_aliases) - len(aws_map)} unmapped)"
    )

    azure_map = match_azure(azure_aliases, azure2_svgs)
    print(
        f"  Azure: {len(azure_map)}/{len(azure_aliases)} matched "
        f"({len(azure_aliases) - len(azure_map)} unmapped)"
    )

    print("\n=== Writing shape map files ===")
    write_map_file(
        "aws",
        "DRAWIO_SHAPE_MAP_AWS",
        aws_map,
        f"jgraph/drawio Sidebar-AWS4.js ({len(aws4_shapes)} shapes)",
    )
    write_map_file(
        "azure",
        "DRAWIO_SHAPE_MAP_AZURE",
        azure_map,
        f"jgraph/drawio img/lib/azure2/ ({total_azure_svgs} SVGs)",
    )

    print("\n=== Unmatched aliases (will use fallback) ===")
    for label, aliases, matched in [
        ("AWS", aws_aliases, aws_map),
        ("Azure", azure_aliases, azure_map),
    ]:
        unmatched = sorted(set(aliases.keys()) - set(matched.keys()))
        if unmatched:
            print(f"  {label} ({len(unmatched)}):")
            for a in unmatched[:20]:
                print(f"    - {a}")
            if len(unmatched) > 20:
                print(f"    ... and {len(unmatched) - 20} more")

    print(
        "\nDone! Run 'poetry run black modules/config/drawio_shape_map_*.py' to format."
    )


if __name__ == "__main__":
    main()
